version: 2.1
jobs:
  test_master:
    docker:
      - image: euantorano/zig:master

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: print zig version
          command: |
            zig version
      - run:
          name: run tests
          command: |
            apk add libx11-dev
            apk add libxft
            zig build-exe src/main.zig -lc -lX11 -lXft -I/usr/include/freetype2
workflows:
  version: 2
  commit:
    jobs:
      - test_master
