version: 2.1
jobs:
  test_master:
    docker:
      - image: eloitor/zig:master

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: print zig version
          command: |
            zig version
      - run:
          name: run tests
          command: |
            zig build-exe src/main.zig -lc -lX11 -lXft -I/usr/include/freetype2
            zig build-exe src/client.zig -lc -lX11
          paralel: true

workflows:
  version: 2
  commit:
    jobs:
      - test_master:
         context: dockerhub
